#include "calendar_system/JapaneseEra.hpp"

#include <cstddef>
#include <stdexcept>
#include <string>

namespace toolbox {
namespace {

const EraMetadata kEraMetadata[] = {
    { TAIKA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 645, 7, 29 },
        { ERA_CALENDAR_JULIAN, 650, 3, 22 }, true,
        "大化" },
    { HAKUCHI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 650, 3, 22 },
        { ERA_CALENDAR_JULIAN, 655, 2, 11 }, true,
        "白雉" },
    { SHUCHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 686, 8, 14 },
        { ERA_CALENDAR_JULIAN, 687, 2, 17 }, true,
        "朱鳥" },
    { TAIHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 701, 5, 3 },
        { ERA_CALENDAR_JULIAN, 704, 6, 16 }, true,
        "大宝" },
    { KEIUN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 704, 6, 16 },
        { ERA_CALENDAR_JULIAN, 708, 2, 7 }, true,
        "慶雲" },
    { WADO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 708, 2, 7 },
        { ERA_CALENDAR_JULIAN, 715, 10, 3 }, true,
        "和銅" },
    { REIKI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 715, 10, 3 },
        { ERA_CALENDAR_JULIAN, 717, 12, 24 }, true,
        "霊亀" },
    { YORO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 717, 12, 24 },
        { ERA_CALENDAR_JULIAN, 724, 3, 3 }, true,
        "養老" },
    { JINKI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 724, 3, 3 },
        { ERA_CALENDAR_JULIAN, 729, 9, 2 }, true,
        "神亀" },
    { TEMPYO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 729, 9, 2 },
        { ERA_CALENDAR_JULIAN, 749, 5, 4 }, true,
        "天平" },
    { TEMPYO_KAMPO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 749, 5, 4 },
        { ERA_CALENDAR_JULIAN, 749, 8, 19 }, true,
        "天平感宝" },
    { TEMPYO_SHOHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 749, 8, 19 },
        { ERA_CALENDAR_JULIAN, 757, 9, 6 }, true,
        "天平勝宝" },
    { TEMPYO_HOJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 757, 9, 6 },
        { ERA_CALENDAR_JULIAN, 765, 2, 1 }, true,
        "天平宝字" },
    { TEMPYO_JINGO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 765, 2, 1 },
        { ERA_CALENDAR_JULIAN, 767, 9, 13 }, true,
        "天平神護" },
    { JINGO_KEIUN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 767, 9, 13 },
        { ERA_CALENDAR_JULIAN, 770, 10, 23 }, true,
        "神護景雲" },
    { HOKI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 770, 10, 23 },
        { ERA_CALENDAR_JULIAN, 781, 1, 30 }, true,
        "宝亀" },
    { TEN_O, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 781, 1, 30 },
        { ERA_CALENDAR_JULIAN, 782, 9, 30 }, true,
        "天応" },
    { ENRYAKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 782, 9, 30 },
        { ERA_CALENDAR_JULIAN, 806, 6, 8 }, true,
        "延暦" },
    { DAIDO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 806, 6, 8 },
        { ERA_CALENDAR_JULIAN, 810, 10, 20 }, true,
        "大同" },
    { KONIN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 810, 10, 20 },
        { ERA_CALENDAR_JULIAN, 824, 2, 8 }, true,
        "弘仁" },
    { TENCHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 824, 2, 8 },
        { ERA_CALENDAR_JULIAN, 834, 2, 14 }, true,
        "天長" },
    { JOWA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 834, 2, 14 },
        { ERA_CALENDAR_JULIAN, 848, 7, 16 }, true,
        "承和" },
    { KAJO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 848, 7, 16 },
        { ERA_CALENDAR_JULIAN, 851, 6, 1 }, true,
        "嘉祥" },
    { NINJU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 851, 6, 1 },
        { ERA_CALENDAR_JULIAN, 854, 12, 23 }, true,
        "仁寿" },
    { SAIKO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 854, 12, 23 },
        { ERA_CALENDAR_JULIAN, 857, 3, 20 }, true,
        "斉衡" },
    { TEN_AN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 857, 3, 20 },
        { ERA_CALENDAR_JULIAN, 859, 5, 20 }, true,
        "天安" },
    { JOGAN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 859, 5, 20 },
        { ERA_CALENDAR_JULIAN, 877, 6, 1 }, true,
        "貞観" },
    { GANGYO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 877, 6, 1 },
        { ERA_CALENDAR_JULIAN, 885, 3, 11 }, true,
        "元慶" },
    { NINNA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 885, 3, 11 },
        { ERA_CALENDAR_JULIAN, 889, 5, 30 }, true,
        "仁和" },
    { KAMPYO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 889, 5, 30 },
        { ERA_CALENDAR_JULIAN, 898, 5, 20 }, true,
        "寛平" },
    { SHOTAI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 898, 5, 20 },
        { ERA_CALENDAR_JULIAN, 901, 8, 31 }, true,
        "昌泰" },
    { ENGI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 901, 8, 31 },
        { ERA_CALENDAR_JULIAN, 923, 5, 29 }, true,
        "延喜" },
    { ENCHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 923, 5, 29 },
        { ERA_CALENDAR_JULIAN, 931, 5, 16 }, true,
        "延長" },
    { JOHEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 931, 5, 16 },
        { ERA_CALENDAR_JULIAN, 938, 6, 22 }, true,
        "承平" },
    { TENKYO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 938, 6, 22 },
        { ERA_CALENDAR_JULIAN, 947, 5, 15 }, true,
        "天慶" },
    { TENRYAKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 947, 5, 15 },
        { ERA_CALENDAR_JULIAN, 957, 11, 21 }, true,
        "天暦" },
    { TENTOKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 957, 11, 21 },
        { ERA_CALENDAR_JULIAN, 961, 3, 5 }, true,
        "天徳" },
    { O_WA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 961, 3, 5 },
        { ERA_CALENDAR_JULIAN, 964, 8, 19 }, true,
        "応和" },
    { KO_HO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 964, 8, 19 },
        { ERA_CALENDAR_JULIAN, 968, 9, 8 }, true,
        "康保" },
    { ANNA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 968, 9, 8 },
        { ERA_CALENDAR_JULIAN, 970, 5, 3 }, true,
        "安和" },
    { TENROKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 970, 5, 3 },
        { ERA_CALENDAR_JULIAN, 974, 1, 16 }, true,
        "天禄" },
    { TEN_EN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 974, 1, 16 },
        { ERA_CALENDAR_JULIAN, 976, 8, 11 }, true,
        "天延" },
    { JOGEN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 976, 8, 11 },
        { ERA_CALENDAR_JULIAN, 978, 12, 31 }, true,
        "貞元" },
    { TENGEN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 978, 12, 31 },
        { ERA_CALENDAR_JULIAN, 983, 5, 29 }, true,
        "天元" },
    { EIKAN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 983, 5, 29 },
        { ERA_CALENDAR_JULIAN, 985, 5, 19 }, true,
        "永観" },
    { KANNA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 985, 5, 19 },
        { ERA_CALENDAR_JULIAN, 987, 5, 5 }, true,
        "寛和" },
    { EIEN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 987, 5, 5 },
        { ERA_CALENDAR_JULIAN, 989, 9, 10 }, true,
        "永延" },
    { EISO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 989, 9, 10 },
        { ERA_CALENDAR_JULIAN, 990, 11, 26 }, true,
        "永祚" },
    { SHORYAKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 990, 11, 26 },
        { ERA_CALENDAR_JULIAN, 995, 3, 25 }, true,
        "正暦" },
    { CHOTOKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 995, 3, 25 },
        { ERA_CALENDAR_JULIAN, 999, 2, 1 }, true,
        "長徳" },
    { CHO_HO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 999, 2, 1 },
        { ERA_CALENDAR_JULIAN, 1004, 8, 8 }, true,
        "長保" },
    { KANKO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1004, 8, 8 },
        { ERA_CALENDAR_JULIAN, 1013, 2, 8 }, true,
        "寛弘" },
    { CHOWA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1013, 2, 8 },
        { ERA_CALENDAR_JULIAN, 1017, 5, 21 }, true,
        "長和" },
    { KAN_NIN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1017, 5, 21 },
        { ERA_CALENDAR_JULIAN, 1021, 3, 17 }, true,
        "寛仁" },
    { JIAN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1021, 3, 17 },
        { ERA_CALENDAR_JULIAN, 1024, 8, 19 }, true,
        "治安" },
    { MANJU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1024, 8, 19 },
        { ERA_CALENDAR_JULIAN, 1028, 8, 18 }, true,
        "万寿" },
    { CHOGEN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1028, 8, 18 },
        { ERA_CALENDAR_JULIAN, 1037, 5, 9 }, true,
        "長元" },
    { CHORYAKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1037, 5, 9 },
        { ERA_CALENDAR_JULIAN, 1040, 12, 16 }, true,
        "長暦" },
    { CHOKYU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1040, 12, 16 },
        { ERA_CALENDAR_JULIAN, 1044, 12, 16 }, true,
        "長久" },
    { KANTOKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1044, 12, 16 },
        { ERA_CALENDAR_JULIAN, 1046, 5, 22 }, true,
        "寛徳" },
    { EISHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1046, 5, 22 },
        { ERA_CALENDAR_JULIAN, 1053, 2, 2 }, true,
        "永承" },
    { TENGI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1053, 2, 2 },
        { ERA_CALENDAR_JULIAN, 1058, 9, 19 }, true,
        "天喜" },
    { KOHEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1058, 9, 19 },
        { ERA_CALENDAR_JULIAN, 1065, 9, 4 }, true,
        "康平" },
    { JIRYAKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1065, 9, 4 },
        { ERA_CALENDAR_JULIAN, 1069, 5, 6 }, true,
        "治暦" },
    { ENKYU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1069, 5, 6 },
        { ERA_CALENDAR_JULIAN, 1074, 9, 16 }, true,
        "延久" },
    { JO_HO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1074, 9, 16 },
        { ERA_CALENDAR_JULIAN, 1077, 12, 5 }, true,
        "承保" },
    { JORYAKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1077, 12, 5 },
        { ERA_CALENDAR_JULIAN, 1081, 3, 22 }, true,
        "承暦" },
    { EI_HO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1081, 3, 22 },
        { ERA_CALENDAR_JULIAN, 1084, 3, 15 }, true,
        "永保" },
    { O_TOKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1084, 3, 15 },
        { ERA_CALENDAR_JULIAN, 1087, 5, 11 }, true,
        "応徳" },
    { KANJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1087, 5, 11 },
        { ERA_CALENDAR_JULIAN, 1095, 1, 23 }, true,
        "寛治" },
    { KA_HO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1095, 1, 23 },
        { ERA_CALENDAR_JULIAN, 1097, 1, 3 }, true,
        "嘉保" },
    { EICHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1097, 1, 3 },
        { ERA_CALENDAR_JULIAN, 1097, 12, 27 }, true,
        "永長" },
    { JOTOKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1097, 12, 27 },
        { ERA_CALENDAR_JULIAN, 1099, 9, 15 }, true,
        "承徳" },
    { KOWA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1099, 9, 15 },
        { ERA_CALENDAR_JULIAN, 1104, 3, 8 }, true,
        "康和" },
    { CHOJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1104, 3, 8 },
        { ERA_CALENDAR_JULIAN, 1106, 5, 13 }, true,
        "長治" },
    { KASHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1106, 5, 13 },
        { ERA_CALENDAR_JULIAN, 1108, 9, 9 }, true,
        "嘉承" },
    { TEN_NIN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1108, 9, 9 },
        { ERA_CALENDAR_JULIAN, 1110, 7, 31 }, true,
        "天仁" },
    { TEN_EI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1110, 7, 31 },
        { ERA_CALENDAR_JULIAN, 1113, 8, 25 }, true,
        "天永" },
    { EIKYU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1113, 8, 25 },
        { ERA_CALENDAR_JULIAN, 1118, 4, 25 }, true,
        "永久" },
    { GEN_EI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1118, 4, 25 },
        { ERA_CALENDAR_JULIAN, 1120, 5, 9 }, true,
        "元永" },
    { HO_AN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1120, 5, 9 },
        { ERA_CALENDAR_JULIAN, 1124, 5, 18 }, true,
        "保安" },
    { TENJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1124, 5, 18 },
        { ERA_CALENDAR_JULIAN, 1126, 2, 15 }, true,
        "天治" },
    { DAIJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1126, 2, 15 },
        { ERA_CALENDAR_JULIAN, 1131, 2, 28 }, true,
        "大治" },
    { TENSHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1131, 2, 28 },
        { ERA_CALENDAR_JULIAN, 1132, 9, 21 }, true,
        "天承" },
    { CHOSHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1132, 9, 21 },
        { ERA_CALENDAR_JULIAN, 1135, 6, 10 }, true,
        "長承" },
    { HO_EN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1135, 6, 10 },
        { ERA_CALENDAR_JULIAN, 1141, 8, 13 }, true,
        "保延" },
    { EIJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1141, 8, 13 },
        { ERA_CALENDAR_JULIAN, 1142, 5, 25 }, true,
        "永治" },
    { KOJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1142, 5, 25 },
        { ERA_CALENDAR_JULIAN, 1144, 3, 28 }, true,
        "康治" },
    { TEN_YO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1144, 3, 28 },
        { ERA_CALENDAR_JULIAN, 1145, 8, 12 }, true,
        "天養" },
    { KYU_AN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1145, 8, 12 },
        { ERA_CALENDAR_JULIAN, 1151, 2, 14 }, true,
        "久安" },
    { NIMPEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1151, 2, 14 },
        { ERA_CALENDAR_JULIAN, 1154, 12, 4 }, true,
        "仁平" },
    { KYUJU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1154, 12, 4 },
        { ERA_CALENDAR_JULIAN, 1156, 5, 18 }, true,
        "久寿" },
    { HOGEN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1156, 5, 18 },
        { ERA_CALENDAR_JULIAN, 1159, 5, 9 }, true,
        "保元" },
    { HEIJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1159, 5, 9 },
        { ERA_CALENDAR_JULIAN, 1160, 2, 18 }, true,
        "平治" },
    { EIRYAKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1160, 2, 18 },
        { ERA_CALENDAR_JULIAN, 1161, 9, 24 }, true,
        "永暦" },
    { O_HO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1161, 9, 24 },
        { ERA_CALENDAR_JULIAN, 1163, 5, 4 }, true,
        "応保" },
    { CHOKAN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1163, 5, 4 },
        { ERA_CALENDAR_JULIAN, 1165, 7, 14 }, true,
        "長寛" },
    { EIMAN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1165, 7, 14 },
        { ERA_CALENDAR_JULIAN, 1166, 9, 23 }, true,
        "永万" },
    { NIN_AN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1166, 9, 23 },
        { ERA_CALENDAR_JULIAN, 1169, 5, 6 }, true,
        "仁安" },
    { KA_O, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1169, 5, 6 },
        { ERA_CALENDAR_JULIAN, 1171, 5, 27 }, true,
        "嘉応" },
    { JO_AN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1171, 5, 27 },
        { ERA_CALENDAR_JULIAN, 1175, 8, 16 }, true,
        "承安" },
    { ANGEN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1175, 8, 16 },
        { ERA_CALENDAR_JULIAN, 1177, 8, 29 }, true,
        "安元" },
    { JISHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1177, 8, 29 },
        { ERA_CALENDAR_JULIAN, 1181, 8, 25 }, true,
        "治承" },
    { YO_WA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1181, 8, 25 },
        { ERA_CALENDAR_JULIAN, 1182, 6, 29 }, true,
        "養和" },
    { JUEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1182, 6, 29 },
        { ERA_CALENDAR_JULIAN, 1184, 5, 27 }, true,
        "寿永" },
    { GENRYAKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1184, 5, 27 },
        { ERA_CALENDAR_JULIAN, 1185, 9, 9 }, true,
        "元暦" },
    { BUNJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1185, 9, 9 },
        { ERA_CALENDAR_JULIAN, 1190, 5, 16 }, true,
        "文治" },
    { KENKYU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1190, 5, 16 },
        { ERA_CALENDAR_JULIAN, 1199, 5, 23 }, true,
        "建久" },
    { SHOJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1199, 5, 23 },
        { ERA_CALENDAR_JULIAN, 1201, 3, 19 }, true,
        "正治" },
    { KENNIN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1201, 3, 19 },
        { ERA_CALENDAR_JULIAN, 1204, 3, 23 }, true,
        "建仁" },
    { GENKYU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1204, 3, 23 },
        { ERA_CALENDAR_JULIAN, 1206, 6, 5 }, true,
        "元久" },
    { KEN_EI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1206, 6, 5 },
        { ERA_CALENDAR_JULIAN, 1207, 11, 16 }, true,
        "建永" },
    { JOGEN_K, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1207, 11, 16 },
        { ERA_CALENDAR_JULIAN, 1211, 4, 23 }, true,
        "承元" },
    { KENRYAKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1211, 4, 23 },
        { ERA_CALENDAR_JULIAN, 1214, 1, 18 }, true,
        "建暦" },
    { KEMPO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1214, 1, 18 },
        { ERA_CALENDAR_JULIAN, 1219, 5, 27 }, true,
        "建保" },
    { JOKYU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1219, 5, 27 },
        { ERA_CALENDAR_JULIAN, 1222, 5, 25 }, true,
        "承久" },
    { JO_O, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1222, 5, 25 },
        { ERA_CALENDAR_JULIAN, 1224, 12, 31 }, true,
        "貞応" },
    { GENNIN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1224, 12, 31 },
        { ERA_CALENDAR_JULIAN, 1225, 5, 28 }, true,
        "元仁" },
    { KAROKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1225, 5, 28 },
        { ERA_CALENDAR_JULIAN, 1228, 1, 18 }, true,
        "嘉禄" },
    { ANTEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1228, 1, 18 },
        { ERA_CALENDAR_JULIAN, 1229, 3, 31 }, true,
        "安貞" },
    { KANGI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1229, 3, 31 },
        { ERA_CALENDAR_JULIAN, 1232, 4, 23 }, true,
        "寛喜" },
    { JOEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1232, 4, 23 },
        { ERA_CALENDAR_JULIAN, 1233, 5, 25 }, true,
        "貞永" },
    { TENPUKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1233, 5, 25 },
        { ERA_CALENDAR_JULIAN, 1234, 11, 27 }, true,
        "天福" },
    { BUNRYAKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1234, 11, 27 },
        { ERA_CALENDAR_JULIAN, 1235, 11, 1 }, true,
        "文暦" },
    { KATEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1235, 11, 1 },
        { ERA_CALENDAR_JULIAN, 1238, 12, 30 }, true,
        "嘉禎" },
    { RYAKUNIN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1238, 12, 30 },
        { ERA_CALENDAR_JULIAN, 1239, 3, 13 }, true,
        "暦仁" },
    { EN_O, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1239, 3, 13 },
        { ERA_CALENDAR_JULIAN, 1240, 8, 5 }, true,
        "延応" },
    { NINJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1240, 8, 5 },
        { ERA_CALENDAR_JULIAN, 1243, 3, 18 }, true,
        "仁治" },
    { KANGEN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1243, 3, 18 },
        { ERA_CALENDAR_JULIAN, 1247, 4, 5 }, true,
        "寛元" },
    { HOJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1247, 4, 5 },
        { ERA_CALENDAR_JULIAN, 1249, 5, 2 }, true,
        "宝治" },
    { KENCHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1249, 5, 2 },
        { ERA_CALENDAR_JULIAN, 1256, 10, 24 }, true,
        "建長" },
    { KOGEN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1256, 10, 24 },
        { ERA_CALENDAR_JULIAN, 1257, 3, 31 }, true,
        "康元" },
    { SHOKA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1257, 3, 31 },
        { ERA_CALENDAR_JULIAN, 1259, 4, 20 }, true,
        "正嘉" },
    { SHOGEN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1259, 4, 20 },
        { ERA_CALENDAR_JULIAN, 1260, 5, 24 }, true,
        "正元" },
    { BUN_O, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1260, 5, 24 },
        { ERA_CALENDAR_JULIAN, 1261, 3, 22 }, true,
        "文応" },
    { KOCHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1261, 3, 22 },
        { ERA_CALENDAR_JULIAN, 1264, 3, 27 }, true,
        "弘長" },
    { BUN_EI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1264, 3, 27 },
        { ERA_CALENDAR_JULIAN, 1275, 5, 22 }, true,
        "文永" },
    { KENJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1275, 5, 22 },
        { ERA_CALENDAR_JULIAN, 1278, 3, 23 }, true,
        "建治" },
    { KO_AN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1278, 3, 23 },
        { ERA_CALENDAR_JULIAN, 1288, 5, 29 }, true,
        "弘安" },
    { SHO_O, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1288, 5, 29 },
        { ERA_CALENDAR_JULIAN, 1293, 9, 6 }, true,
        "正応" },
    { EININ, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1293, 9, 6 },
        { ERA_CALENDAR_JULIAN, 1299, 5, 25 }, true,
        "永仁" },
    { SHO_AN_K, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1299, 5, 25 },
        { ERA_CALENDAR_JULIAN, 1302, 12, 10 }, true,
        "正安" },
    { KENGEN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1302, 12, 10 },
        { ERA_CALENDAR_JULIAN, 1303, 9, 16 }, true,
        "乾元" },
    { KAGEN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1303, 9, 16 },
        { ERA_CALENDAR_JULIAN, 1307, 1, 18 }, true,
        "嘉元" },
    { TOKUJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1307, 1, 18 },
        { ERA_CALENDAR_JULIAN, 1308, 11, 22 }, true,
        "徳治" },
    { ENKYO_K, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1308, 11, 22 },
        { ERA_CALENDAR_JULIAN, 1311, 5, 17 }, true,
        "延慶" },
    { O_CHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1311, 5, 17 },
        { ERA_CALENDAR_JULIAN, 1312, 4, 27 }, true,
        "応長" },
    { SHOWA_K, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1312, 4, 27 },
        { ERA_CALENDAR_JULIAN, 1317, 3, 16 }, true,
        "正和" },
    { BUMPO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1317, 3, 16 },
        { ERA_CALENDAR_JULIAN, 1319, 5, 18 }, true,
        "文保" },
    { GEN_O, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1319, 5, 18 },
        { ERA_CALENDAR_JULIAN, 1321, 3, 22 }, true,
        "元応" },
    { GENKYO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1321, 3, 22 },
        { ERA_CALENDAR_JULIAN, 1324, 12, 25 }, true,
        "元亨" },
    { SHOCHU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1324, 12, 25 },
        { ERA_CALENDAR_JULIAN, 1326, 5, 28 }, true,
        "正中" },
    { KARYAKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1326, 5, 28 },
        { ERA_CALENDAR_JULIAN, 1329, 9, 22 }, true,
        "嘉暦" },
    { GENTOKU, ERA_AUTHORITY_SOUTHERN,
        { ERA_CALENDAR_JULIAN, 1329, 9, 22 },
        { ERA_CALENDAR_JULIAN, 1331, 9, 11 }, true,
        "元徳" },
    { GENKO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1331, 9, 11 },
        { ERA_CALENDAR_JULIAN, 1334, 3, 5 }, true,
        "元弘" },
    { SHOKYO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1332, 5, 23 },
        { ERA_CALENDAR_JULIAN, 1333, 7, 7 }, true,
        "正慶" },
    { KENMU, ERA_AUTHORITY_SOUTHERN,
        { ERA_CALENDAR_JULIAN, 1334, 3, 5 },
        { ERA_CALENDAR_JULIAN, 1336, 4, 11 }, true,
        "建武" },
    { ENGEN, ERA_AUTHORITY_SOUTHERN,
        { ERA_CALENDAR_JULIAN, 1336, 4, 11 },
        { ERA_CALENDAR_JULIAN, 1340, 5, 25 }, true,
        "延元" },
    { KOKOKU, ERA_AUTHORITY_SOUTHERN,
        { ERA_CALENDAR_JULIAN, 1340, 5, 25 },
        { ERA_CALENDAR_JULIAN, 1347, 1, 20 }, true,
        "興国" },
    { SHOHEI, ERA_AUTHORITY_SOUTHERN,
        { ERA_CALENDAR_JULIAN, 1347, 1, 20 },
        { ERA_CALENDAR_JULIAN, 1370, 8, 16 }, true,
        "正平" },
    { KENTOKU, ERA_AUTHORITY_SOUTHERN,
        { ERA_CALENDAR_JULIAN, 1370, 8, 16 },
        { ERA_CALENDAR_JULIAN, 1372, 5, 1 }, true,
        "建徳" },
    { BUNCHU, ERA_AUTHORITY_SOUTHERN,
        { ERA_CALENDAR_JULIAN, 1372, 5, 1 },
        { ERA_CALENDAR_JULIAN, 1375, 6, 26 }, true,
        "文中" },
    { TENJU, ERA_AUTHORITY_SOUTHERN,
        { ERA_CALENDAR_JULIAN, 1375, 6, 26 },
        { ERA_CALENDAR_JULIAN, 1381, 3, 6 }, true,
        "天授" },
    { KOWA_S, ERA_AUTHORITY_SOUTHERN,
        { ERA_CALENDAR_JULIAN, 1381, 3, 6 },
        { ERA_CALENDAR_JULIAN, 1384, 5, 18 }, true,
        "弘和" },
    { GENCHU, ERA_AUTHORITY_SOUTHERN,
        { ERA_CALENDAR_JULIAN, 1384, 5, 18 },
        { ERA_CALENDAR_JULIAN, 1392, 11, 19 }, true,
        "元中" },
    { RYAKUO, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1338, 10, 11 },
        { ERA_CALENDAR_JULIAN, 1342, 6, 1 }, true,
        "暦応" },
    { KOEI, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1342, 6, 1 },
        { ERA_CALENDAR_JULIAN, 1345, 11, 15 }, true,
        "康永" },
    { JOWA_N, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1345, 11, 15 },
        { ERA_CALENDAR_JULIAN, 1350, 4, 4 }, true,
        "貞和" },
    { KAN_O, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1350, 4, 4 },
        { ERA_CALENDAR_JULIAN, 1352, 11, 4 }, true,
        "観応" },
    { BUNNA, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1352, 11, 4 },
        { ERA_CALENDAR_JULIAN, 1356, 4, 29 }, true,
        "文和" },
    { EMBUN, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1356, 4, 29 },
        { ERA_CALENDAR_JULIAN, 1361, 5, 4 }, true,
        "延文" },
    { KO_AN_N, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1361, 5, 4 },
        { ERA_CALENDAR_JULIAN, 1362, 10, 11 }, true,
        "康安" },
    { JOJI_N, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1362, 10, 11 },
        { ERA_CALENDAR_JULIAN, 1368, 3, 7 }, true,
        "貞治" },
    { O_AN, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1368, 3, 7 },
        { ERA_CALENDAR_JULIAN, 1375, 3, 29 }, true,
        "応安" },
    { EIWA, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1375, 3, 29 },
        { ERA_CALENDAR_JULIAN, 1379, 4, 9 }, true,
        "永和" },
    { KORYAKU, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1379, 4, 9 },
        { ERA_CALENDAR_JULIAN, 1381, 3, 20 }, true,
        "康暦" },
    { EITOKU, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1381, 3, 20 },
        { ERA_CALENDAR_JULIAN, 1384, 3, 19 }, true,
        "永徳" },
    { SHITOKU, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1384, 3, 19 },
        { ERA_CALENDAR_JULIAN, 1387, 10, 5 }, true,
        "至徳" },
    { KAKYO, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1387, 10, 5 },
        { ERA_CALENDAR_JULIAN, 1389, 3, 7 }, true,
        "嘉慶" },
    { KO_O, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1389, 3, 7 },
        { ERA_CALENDAR_JULIAN, 1390, 4, 12 }, true,
        "康応" },
    { MEITOKU, ERA_AUTHORITY_NORTHERN,
        { ERA_CALENDAR_JULIAN, 1390, 4, 12 },
        { ERA_CALENDAR_JULIAN, 1394, 8, 2 }, true,
        "明徳" },
    { OEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1394, 8, 2 },
        { ERA_CALENDAR_JULIAN, 1428, 6, 10 }, true,
        "応永" },
    { SHOCHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1428, 6, 10 },
        { ERA_CALENDAR_JULIAN, 1429, 10, 3 }, true,
        "正長" },
    { EIKYO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1429, 10, 3 },
        { ERA_CALENDAR_JULIAN, 1441, 3, 10 }, true,
        "永享" },
    { KAKITSU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1441, 3, 10 },
        { ERA_CALENDAR_JULIAN, 1444, 2, 23 }, true,
        "嘉吉" },
    { BUN_AN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1444, 2, 23 },
        { ERA_CALENDAR_JULIAN, 1449, 8, 16 }, true,
        "文安" },
    { HOTOKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1449, 8, 16 },
        { ERA_CALENDAR_JULIAN, 1452, 8, 10 }, true,
        "宝徳" },
    { KYOTOKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1452, 8, 10 },
        { ERA_CALENDAR_JULIAN, 1455, 9, 6 }, true,
        "享徳" },
    { KOSHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1455, 9, 6 },
        { ERA_CALENDAR_JULIAN, 1457, 10, 16 }, true,
        "康正" },
    { CHOROKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1457, 10, 16 },
        { ERA_CALENDAR_JULIAN, 1461, 2, 1 }, true,
        "長禄" },
    { KANSHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1461, 2, 1 },
        { ERA_CALENDAR_JULIAN, 1466, 3, 14 }, true,
        "寛正" },
    { BUNSHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1466, 3, 14 },
        { ERA_CALENDAR_JULIAN, 1467, 4, 9 }, true,
        "文正" },
    { ONIN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1467, 4, 9 },
        { ERA_CALENDAR_JULIAN, 1469, 6, 8 }, true,
        "応仁" },
    { BUNMEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1469, 6, 8 },
        { ERA_CALENDAR_JULIAN, 1487, 8, 9 }, true,
        "文明" },
    { CHOKYO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1487, 8, 9 },
        { ERA_CALENDAR_JULIAN, 1489, 9, 16 }, true,
        "長享" },
    { ENTOKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1489, 9, 16 },
        { ERA_CALENDAR_JULIAN, 1492, 8, 12 }, true,
        "延徳" },
    { MEI_O, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1492, 8, 12 },
        { ERA_CALENDAR_JULIAN, 1501, 3, 18 }, true,
        "明応" },
    { BUNKI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1501, 3, 18 },
        { ERA_CALENDAR_JULIAN, 1504, 3, 16 }, true,
        "文亀" },
    { EISHO_M, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1504, 3, 16 },
        { ERA_CALENDAR_JULIAN, 1521, 9, 23 }, true,
        "永正" },
    { TAIEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1521, 9, 23 },
        { ERA_CALENDAR_JULIAN, 1528, 9, 3 }, true,
        "大永" },
    { KYOROKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1528, 9, 3 },
        { ERA_CALENDAR_JULIAN, 1532, 8, 29 }, true,
        "享禄" },
    { TEMBUN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1532, 8, 29 },
        { ERA_CALENDAR_JULIAN, 1555, 11, 7 }, true,
        "天文" },
    { KOJI_M, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1555, 11, 7 },
        { ERA_CALENDAR_JULIAN, 1558, 3, 18 }, true,
        "弘治" },
    { EIROKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1558, 3, 18 },
        { ERA_CALENDAR_JULIAN, 1570, 5, 27 }, true,
        "永禄" },
    { GENKI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1570, 5, 27 },
        { ERA_CALENDAR_JULIAN, 1573, 8, 25 }, true,
        "元亀" },
    { TENSHO_A, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_JULIAN, 1573, 8, 25 },
        { ERA_CALENDAR_GREGORIAN, 1593, 1, 10 }, true,
        "天正" },
    { BUNROKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1593, 1, 10 },
        { ERA_CALENDAR_GREGORIAN, 1596, 12, 16 }, true,
        "文禄" },
    { KEICHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1596, 12, 16 },
        { ERA_CALENDAR_GREGORIAN, 1615, 9, 5 }, true,
        "慶長" },
    { GENNA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1615, 9, 5 },
        { ERA_CALENDAR_GREGORIAN, 1624, 4, 17 }, true,
        "元和" },
    { KAN_EI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1624, 4, 17 },
        { ERA_CALENDAR_GREGORIAN, 1645, 1, 13 }, true,
        "寛永" },
    { SHO_HO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1645, 1, 13 },
        { ERA_CALENDAR_GREGORIAN, 1648, 4, 7 }, true,
        "正保" },
    { KEIAN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1648, 4, 7 },
        { ERA_CALENDAR_GREGORIAN, 1652, 10, 20 }, true,
        "慶安" },
    { JO_O_E, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1652, 10, 20 },
        { ERA_CALENDAR_GREGORIAN, 1655, 5, 18 }, true,
        "承応" },
    { MEIREKI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1655, 5, 18 },
        { ERA_CALENDAR_GREGORIAN, 1658, 8, 21 }, true,
        "明暦" },
    { MANJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1658, 8, 21 },
        { ERA_CALENDAR_GREGORIAN, 1661, 5, 23 }, true,
        "万治" },
    { KANBUN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1661, 5, 23 },
        { ERA_CALENDAR_GREGORIAN, 1673, 10, 30 }, true,
        "寛文" },
    { EMPO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1673, 10, 30 },
        { ERA_CALENDAR_GREGORIAN, 1681, 11, 9 }, true,
        "延宝" },
    { TENNA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1681, 11, 9 },
        { ERA_CALENDAR_GREGORIAN, 1684, 4, 5 }, true,
        "天和" },
    { JOKYO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1684, 4, 5 },
        { ERA_CALENDAR_GREGORIAN, 1688, 10, 23 }, true,
        "貞享" },
    { GENROKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1688, 10, 23 },
        { ERA_CALENDAR_GREGORIAN, 1704, 4, 16 }, true,
        "元禄" },
    { HOEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1704, 4, 16 },
        { ERA_CALENDAR_GREGORIAN, 1711, 6, 11 }, true,
        "宝永" },
    { SHOTOKU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1711, 6, 11 },
        { ERA_CALENDAR_GREGORIAN, 1716, 8, 9 }, true,
        "正徳" },
    { KYO_HO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1716, 8, 9 },
        { ERA_CALENDAR_GREGORIAN, 1736, 6, 7 }, true,
        "享保" },
    { GEMBUN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1736, 6, 7 },
        { ERA_CALENDAR_GREGORIAN, 1741, 4, 12 }, true,
        "元文" },
    { KAMPO_E, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1741, 4, 12 },
        { ERA_CALENDAR_GREGORIAN, 1744, 4, 3 }, true,
        "寛保" },
    { ENKYO_E, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1744, 4, 3 },
        { ERA_CALENDAR_GREGORIAN, 1748, 8, 5 }, true,
        "延享" },
    { KAN_EN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1748, 8, 5 },
        { ERA_CALENDAR_GREGORIAN, 1751, 12, 14 }, true,
        "寛延" },
    { HOREKI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1751, 12, 14 },
        { ERA_CALENDAR_GREGORIAN, 1764, 6, 30 }, true,
        "宝暦" },
    { MEIWA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1764, 6, 30 },
        { ERA_CALENDAR_GREGORIAN, 1772, 12, 10 }, true,
        "明和" },
    { AN_EI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1772, 12, 10 },
        { ERA_CALENDAR_GREGORIAN, 1781, 4, 25 }, true,
        "安永" },
    { TENMEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1781, 4, 25 },
        { ERA_CALENDAR_GREGORIAN, 1789, 2, 19 }, true,
        "天明" },
    { KANSEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1789, 2, 19 },
        { ERA_CALENDAR_GREGORIAN, 1801, 3, 19 }, true,
        "寛政" },
    { KYO_WA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1801, 3, 19 },
        { ERA_CALENDAR_GREGORIAN, 1804, 3, 22 }, true,
        "享和" },
    { BUNKA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1804, 3, 22 },
        { ERA_CALENDAR_GREGORIAN, 1818, 5, 26 }, true,
        "文化" },
    { BUNSEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1818, 5, 26 },
        { ERA_CALENDAR_GREGORIAN, 1831, 1, 23 }, true,
        "文政" },
    { TEMPO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1831, 1, 23 },
        { ERA_CALENDAR_GREGORIAN, 1845, 1, 9 }, true,
        "天保" },
    { KOKA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1845, 1, 9 },
        { ERA_CALENDAR_GREGORIAN, 1848, 4, 1 }, true,
        "弘化" },
    { KAEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1848, 4, 1 },
        { ERA_CALENDAR_GREGORIAN, 1855, 1, 15 }, true,
        "嘉永" },
    { ANSEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1855, 1, 15 },
        { ERA_CALENDAR_GREGORIAN, 1860, 4, 8 }, true,
        "安政" },
    { MAN_EN, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1860, 4, 8 },
        { ERA_CALENDAR_GREGORIAN, 1861, 3, 29 }, true,
        "万延" },
    { BUNKYU, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1861, 3, 29 },
        { ERA_CALENDAR_GREGORIAN, 1864, 3, 27 }, true,
        "文久" },
    { GENJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1864, 3, 27 },
        { ERA_CALENDAR_GREGORIAN, 1865, 5, 1 }, true,
        "元治" },
    { KEI_O, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1865, 5, 1 },
        { ERA_CALENDAR_GREGORIAN, 1868, 10, 23 }, true,
        "慶応" },
    { MEIJI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1868, 1, 25 },
        { ERA_CALENDAR_GREGORIAN, 1912, 7, 29 }, true,
        "明治" },
    { TAISHO, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1912, 7, 30 },
        { ERA_CALENDAR_GREGORIAN, 1926, 12, 24 }, true,
        "大正" },
    { SHOWA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1926, 12, 25 },
        { ERA_CALENDAR_GREGORIAN, 1989, 1, 7 }, true,
        "昭和" },
    { HEISEI, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 1989, 1, 8 },
        { ERA_CALENDAR_GREGORIAN, 2019, 4, 30 }, true,
        "平成" },
    { REIWA, ERA_AUTHORITY_STANDARD,
        { ERA_CALENDAR_GREGORIAN, 2019, 5, 1 },
        { ERA_CALENDAR_GREGORIAN, 0, 0, 0 }, false,
        "令和" },
};

struct EraMetadataSizeCheck {
    int dummy[sizeof(kEraMetadata) / sizeof(kEraMetadata[0]) ==
                                        static_cast<std::size_t>(END_OF_ERA)
                                ? 1
                                : -1];
};

}  // namespace

std::string era_to_kanji(JapaneseEra e) {
  if (e < 0 || e >= END_OF_ERA) {
    throw std::out_of_range("era_to_kanji: invalid era");
  }
  return kEraMetadata[e].kanji;
}

const EraMetadata& get_era_metadata(JapaneseEra era) {
  if (era < 0 || era >= END_OF_ERA) {
    throw std::out_of_range("get_era_metadata: invalid era");
  }
  return kEraMetadata[era];
}

std::size_t era_count() {
    return sizeof(kEraMetadata) / sizeof(kEraMetadata[0]);
}

}  // namespace toolbox

